# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.title }}.

title: "mincnote"
name: "mincnote"
description: ""
url: "https://smc5720.github.io"
baseurl: ""
repository: "smc5720/smc5720.github.io"
remote_theme: "mmistakes/minimal-mistakes"

# Author settings
author:
  avatar: "/assets/images/rico.png"

# Sidebar settings
sidebar:
  enabled: true
  nav: true
  sticky: true
  profile: true
  social: true

# Minimal Mistakes Theme Settings
layout: single
author_profile: true
read_time: true
share: true
comments: true

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - node_modules
  - Rakefile
  - README.md

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      share: true
      related: true
      comments: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/smc5720"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:your-email@example.com"

collections:
  posts:
    output: true
    permalink: /:collection/:name/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Social sharing
social_share:
  twitter: true
  facebook: true
  linkedin: true

# Comments
comments:
  provider: "disqus"
  disqus:
    shortname: "your-disqus-shortname"

# Analytics
analytics:
  provider: "google"
  google:
    tracking_id: ""

# Search
search: true
search_full_content: true

# Related posts
related_posts:
  threshold: 3
  max_related: 3

# Archives
archives:
  layout: "archive"
  permalink: /archives/:year/:month/:day/:title/
  enabled: true

# Categories
categories:
  layout: "category"
  permalink: /category/:name/

# Tags
tags:
  layout: "tag"
  permalink: /tag/:name/

# Sitemap
sitemap:
  changefreq: weekly
  priority: 0.5 