# Site settings
title: "My Personal Blog"
name: "개인 블로그"
description: "개발과 일상에 대한 생각을 담는 공간"
url: "https://smc5720.github.io"
baseurl: ""

# Author settings
author:
  name: "블로그 주인"
  avatar: "/assets/images/profile.jpg"
  bio: "개발자이자 블로거"
  location: "대한민국"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/smc5720"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:your-email@example.com"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
paginate: 5
paginate_path: "/page/:num/"

# Collections
collections:
  posts:
    output: true
    permalink: /:collection/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "블로그 주인"
      comments: true
      share: true
      related: true
      read_time: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Social sharing
social_share:
  twitter: true
  facebook: true
  linkedin: true

# Comments
comments:
  provider: "disqus"
  disqus:
    shortname: "your-disqus-shortname"

# Analytics
analytics:
  provider: "google"
  google:
    tracking_id: ""

# Search
search: true
search_full_content: true

# Reading time
reading_time: true

# Related posts
related: true
related_posts:
  threshold: 3
  max_related: 3

# Archives
archives:
  layout: "archive"
  permalink: /archives/:year/:month/:day/:title/
  enabled: true

# Categories
categories:
  layout: "category"
  permalink: /category/:name/

# Tags
tags:
  layout: "tag"
  permalink: /tag/:name/

# Sitemap
sitemap:
  changefreq: weekly
  priority: 0.5 